# Generated by Django 3.2.21 on 2023-11-29 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Declarant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=8)),
                ('mail', models.CharField(max_length=60)),
                ('nni', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Engin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('numero_serie', models.IntegerField()),
                ('etat', models.BooleanField(default=False)),
                ('numero_matricule', models.CharField(default=' ', max_length=20)),
                ('couleur', models.CharField(max_length=50)),
                ('source_enregie', models.CharField(max_length=50)),
                ('declarant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engin.declarant')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele_genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele_marque', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trouver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engin.engin')),
            ],
        ),
        migrations.AddField(
            model_name='engin',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engin.genre'),
        ),
        migrations.AddField(
            model_name='engin',
            name='marque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engin.marque'),
        ),
    ]
